<a href="https://colab.research.google.com/github/Varun-Mayilvaganan/Machine_Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from time import process_time #time taken=>start
nd = np.array([1,2,3])
start = process_time()
nd = [i*5 for i in nd]#list compre
end = process_time()#end
print(end-start)

0.00015722300000042821


In [ ]:
nde = [i for i in range(3)]
start = process_time()
nd = [i*5 for i in nde]
end = process_time()
print(end-start)

0.00017066799999998494


In [ ]:
nd = np.array([[1,2,3]])
nd.shape

(1, 3)

In [ ]:
a = np.arange(6)#0,1,2,3,4,5 a
a2 = a[0:3]
a3 = a[np.newaxis, 0:2]
a2.shape
print(a)
print(a2)
print(a3)

[0 1 2 3 4 5]
[0 1 2]
[[0 1]]


In [ ]:
a = np.ones(5, dtype = np.int64)
b = np.empty(3, dtype = np.int64)
b[0] = 1
b[1] = 2
b[2] = 3
print(b)

[1 2 3]


In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
b = np.array([(1,2,35,6,7)])
b.shape

(1, 5)

In [ ]:
np.linspace(0, 5, num=3)

array([0. , 2.5, 5. ])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# a = np.array([1, 2, 3, 4])
# b = np.array([5, 6, 7, 8])
# np.concatenate((a,b))
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [9, 8]])
np.concatenate((x,y), axis =1)

array([[1, 2, 5, 6],
       [3, 4, 9, 8]])

In [9]:
ex = np.array([
            (1,2,3),
             (4,4,6),
            [1,2,30],
             [3,5,7],
            ])
print(ex.ndim)
print(ex.size)
print(ex.shape)
print(ex.reshape(3,4))
print(np.transpose(ex))

2
12
(4, 3)
[[ 1  2  3  4]
 [ 4  6  1  2]
 [30  3  5  7]]
[[ 1  4  1  3]
 [ 2  4  2  5]
 [ 3  6 30  7]]


In [ ]:
a = np.arange(6).reshape(3,2)
print(a)
np.reshape(a, newshape=(2,3),order='F')

[[0 1]
 [2 3]
 [4 5]]


array([[0, 4, 3],
       [2, 1, 5]])

In [ ]:
a = np.eye(4,dtype=int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
b = np.random.random((3,4))
b

array([[0.90031479, 0.70318613, 0.14318309, 0.97596909],
       [0.96424294, 0.73479508, 0.78722167, 0.19983175],
       [0.54425776, 0.36457399, 0.45906734, 0.4317779 ]])

In [ ]:
c = np.random.randint(1,5,(1,2))
c

array([[2, 3]])

In [5]:
a = np.random.randint(10,100,(3,3))
b = np.random.randint(10,100,(3,3))
print(a)
print(b)
np.add(a,b)

[[58 10 14]
 [20 82 64]
 [49 40 71]]
[[79 23 41]
 [81 33 78]
 [39 34 38]]


array([[137,  33,  55],
       [101, 115, 142],
       [ 88,  74, 109]])